import fivechesslib
from fivechesslib import BLACK_CHESS, NOBODY_WIN, WHITE_CHESS, NOTHING, BLACK_WIN, WHITE_WIN

chess_board = [
    [NOTHING, NOTHING, BLACK_CHESS, NOTHING, NOTHING],
    [NOTHING, WHITE_CHESS, BLACK_CHESS, WHITE_CHESS, NOTHING],
    [NOTHING, NOTHING, BLACK_CHESS, BLACK_CHESS, BLACK_CHESS],
    [NOTHING, NOTHING, BLACK_CHESS, BLACK_CHESS, NOTHING],
    [NOTHING, NOTHING, BLACK_CHESS, BLACK_CHESS, NOTHING]
]

assert fivechesslib.__check_win_vertically__(chess_board) == BLACK_WIN

print('pass!')





